<a href="https://colab.research.google.com/github/Mikhailo88/KSVDKyrs3/blob/main/Lr1_Olkhovenko.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Був присутній на парі

In [ ]:
import numpy as np
np.__version__

'2.0.2'

In [ ]:
v = np.array([1, 2, 3, 4, 5], dtype = float)
v

array([1., 2., 3., 4., 5.])

In [ ]:
v[0]

np.float64(1.0)

In [ ]:
v[-1]

np.float64(5.0)

In [ ]:
# 2x3
e = np.array([[1, 2, 3],
              [4, 5, 6]])
e

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# a23
e[1, 2]

np.int64(6)

In [ ]:
# a11
e[0, 0]

np.int64(1)

In [ ]:
# Тип
e.dtype

dtype('int64')

In [ ]:
e.size

6

In [ ]:
e.shape

(2, 3)

In [ ]:
# 3x3
a = np.array([[1, 5, 3], [3, 2, 6], [2, 8, 4]])
a

array([[1, 5, 3],
       [3, 2, 6],
       [2, 8, 4]])

In [ ]:
b = np.matrix([[3, 5, 8], [1, 2, 9], [8, 4, 7]])
b

matrix([[3, 5, 8],
        [1, 2, 9],
        [8, 4, 7]])

In [ ]:
diag_a = np.diag(a)
diag_a

array([1, 2, 4])

In [ ]:
diag_a = np.diag(diag_a)
diag_a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 4]])

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros((3, 3), dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
np.random.randint(11, size=(4, 4))

array([[ 4,  2, 10,  5],
       [ 0,  1,  6,  0],
       [ 6,  2,  2,  7],
       [ 9,  3,  1,  9]])

In [ ]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
np.ones((3, 3), dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [ ]:
np.arange(2, 9, 2)

array([2, 4, 6, 8])

In [ ]:
np.linspace(0, 20, 5)

array([ 0.,  5., 10., 15., 20.])

In [ ]:
c = np.array([[4, 2, 3], [1, 7, 6], [9, 4, 8]])
c

array([[4, 2, 3],
       [1, 7, 6],
       [9, 4, 8]])

In [ ]:
c.transpose()

array([[4, 1, 9],
       [2, 7, 4],
       [3, 6, 8]])

In [ ]:
c.T

array([[4, 1, 9],
       [2, 7, 4],
       [3, 6, 8]])

In [ ]:
# Визначник
c = np.array([[1, 2], [3, 4]])
c

array([[1, 2],
       [3, 4]])

In [ ]:
c_det = np.linalg.det(c)
c_det.round(2)

np.float64(-2.0)

In [ ]:
# Множення на число
a = np.matrix([[4, 1, 9], [8, 3, 2]])
c = 3 * a
c

matrix([[12,  3, 27],
        [24,  9,  6]])

In [ ]:
# Додавання
a = np.matrix([[9, 7, 3], [5, 1, 8]])
b = np.matrix([[3, 6, 2], [10, 9, 12]])
c = a + b
c

matrix([[12, 13,  5],
        [15, 10, 20]])

In [ ]:
# Добуток
a = np.matrix([[3, 2], [7, 1]])
b = np.matrix([[9, 5], [4, 6]])
c = np.dot(a, b)
c

matrix([[35, 27],
        [67, 41]])

In [ ]:
#Поелементний добуток
np.multiply(a, b)

matrix([[27, 10],
        [28,  6]])

In [ ]:
a/b

matrix([[0.33333333, 0.4       ],
        [1.75      , 0.16666667]])

In [ ]:
np.divide(a, b)

matrix([[0.33333333, 0.4       ],
        [1.75      , 0.16666667]])

In [ ]:
# Обернена
a = np.matrix([[1, -3], [2, 5]])

a_inv = np.linalg.inv(a)
a_inv

matrix([[ 0.45454545,  0.27272727],
        [-0.18181818,  0.09090909]])

In [ ]:
# Ранг
rank = np.linalg.matrix_rank(a)
rank

np.int64(2)

In [ ]:
a = np.array([[2, 8, 1], [9, 5, 6]])
b = np.array([[7, 6, 2], [10, 9, 12]])

c1 =  a*b
print("Поелементний добуток:")
print(c1)

Поелементний добуток:
[[14 48  2]
 [90 45 72]]


In [ ]:
a = np.array([[0, -3, 4],
              [-2, 0, 1],
              [3, 1, 0]])


eigenvalues, eigenvectors = np.linalg.eig(a)


In [ ]:
print("V:")
print(eigenvalues)

V:
[-4.75160387  3.81340254  0.93820133]


In [ ]:
print("\nW:")
print(eigenvectors)


W:
[[-0.72485782 -0.78990643 -0.08598698]
 [-0.42001841  0.2698813   0.80661326]
 [ 0.54604549 -0.55064682  0.58479167]]
